<?php

namespace AppBundle\Repository;

/**
 * DivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArrayByUnidadId($unidadId)
    {
        $em = $this->getEntityManager();

        $query="
                SELECT d 
                    FROM AppBundle:Division d
                        JOIN d.unidad u 
                    WHERE u.id = :unidadId
        ";

        $consulta = $em->createQuery($query);
        $consulta->setParameter('unidadId', $unidadId);

        return $consulta->getArrayResult();
    }

    public function getByUnidadId($unidadId)
    {
        $em = $this->getEntityManager();

        $query="
                SELECT d 
                    FROM AppBundle:Division d
                        JOIN d.unidad u 
                    WHERE u.id = :unidadId
        ";

        $consulta = $em->createQuery($query);
        $consulta->setParameter('unidadId', $unidadId);

        return $consulta->getResult();
    }
}
