<?php

namespace AppBundle\Repository;

/**
 * PrefullDictamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefullDictamenRepository extends \Doctrine\ORM\EntityRepository
{
}
