<?php

namespace AppBundle\Repository;

/**
 * TiempoDedicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiempoDedicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
