# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
           AppBundle\Entity\Usuario: bcrypt
           AppBundle\Entity\Aspirante: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
    #    in_memory:
    #       memory: ~
         todos:
                       chain:
                          providers: [ aspirante, our_db_provider]

                   aspirante:
                     entity: {class: AppBundle\Entity\Aspirante, property: rfc}
                   our_db_provider:
                     entity: {class: AppBundle\Entity\Usuario, property: numeroEconomico }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        form_login:
            check_path: login_check
            login_path: login_form

        logout:
            path: logout
            target: login_form
        remember_me:
            secret:   '%secret%'
            lifetime: 36000
            path:     /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }